email: "your_email@example.com"
password: "email_password"
user_name: "user_name"
signature: "Placeholder signature"
excel_path: Excel Spreadsheet Example/TasksSpreadsheetExample.xlsx # change this to the path of your Excel spreadsheet
sheet_name: 
- Daily_Tasks
- Report_Selection
- Recipients
